### ISSUE TITLE
Build with POCL is failing

### ISSUE THREAD

**Issue by kannaiah** [Acellera/swan#1]
I'm building with CUDA=no and POCL latest revision 
To make it build I added `-DCL_USE_DEPRECATED_OPENCL_1_2_APIS` to `OPENCL_FLAGS`

```
cd src; make
make[1]: Entering directory `/mnt/c/work/swan/src'
gcc  -g -o ../bin/swan-to-asc to-asc.c
gcc  -g -o ../bin/swan-oclc oclc.c -I/usr/local/lib/x86_64-linux-gnu/include  -L/usr/local/lib/x86_64-linux-gnu/lib64  -lOpenCL -DOPENCL=yes  -g -ggdb -O0 -lm -DOPENCL_FROM_SOURCE -DCL_USE_DEPRECATED_OPENCL_1_2_APIS
PATH="/mnt/c/work/sollya/install/bin:/mnt/c/work/android-sdk/platform-tools:/mnt/c/work/sollya/install/bin:/mnt/c/work/android-sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games":../bin; ../bin/swan --opencl fastfill_ocl.kh fastfill.cu
Building for OpenCL
swan-oclc: /usr/local/lib/x86_64-linux-gnu/libOpenCL.so.1: no version information available (required by swan-oclc)
ERROR at 65 : -1
Compilation failed : look in _swanW8AZ56.in
make[1]: *** [fastfill] Error 157
make[1]: Leaving directory `/mnt/c/work/swan/src'
make: *** [all] Error 2
```

The function is seems to bee failing is empty kernel `canary`

**Comment by mj-harvey** [comment]
Hi,From memory, Error 1001 means that the opencl runtime can't enumerate any platforms‎. Is the pocl icd installed correctly? Do you have an oclinfo program to test the pocl install with?Matt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: kannaiahSent: Saturday, 4 February 2017 11:57To: Acellera/swanReply To: Acellera/swanCc: SubscribedSubject: [Acellera/swan] Build with POCL is failing (#1)I'm building with CUDA=no and POCL latest revision
To make it build I added -DCL_USE_DEPRECATED_OPENCL_1_2_APIS to OPENCL_FLAGS
cd src; make
make[1]: Entering directory `/mnt/c/work/swan/src'
gcc  -g -o ../bin/swan-to-asc to-asc.c
gcc  -g -o ../bin/swan-oclc oclc.c -I/usr/local/cuda/include  -L/usr/local/cuda/lib64  -lOpenCL -DOPENCL=yes   -lm -DOPENCL_FROM_SOURCE -DCL_USE_DEPRECATED_OPENCL_1_2_APIS
PATH="/mnt/c/work/swan/bin:/mnt/c/work/sollya/install/bin:/mnt/c/work/android-sdk/platform-tools:/usr/lib/llvm-3.9/bin/:/mnt/c/work/sollya/install/bin:/mnt/c/work/android-sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games":../bin; ../bin/swan --opencl fastfill_ocl.kh fastfill.cu
Building for OpenCL
ERROR at 235 : -1001
Compilation failed : look in _swandqIVdr.in
make[1]: *** [fastfill] Error 157
make[1]: Leaving directory `/mnt/c/work/swan/src'
make: *** [all] Error 2

The function is seems to bee failing is empty kernel canary

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Acellera/swan","title":"Acellera/swan","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Acellera/swan"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Build with POCL is failing (#1)"}],"action":{"name":"View Issue","url":"https://github.com/Acellera/swan/issues/1"}}}
